import { createAudioPlayer, type AudioPlayer } from 'expo-audio';
import { useSettingsStore } from '@/store/settingsStore';

// Placeholder tones generated by scripts/generate-sounds.mjs (pure sine-wave
// synthesis, no external assets) — swap these 5 files for real sound design
// later without touching any call site.
const SOUND_SOURCES = {
  correct: require('../assets/sounds/correct.wav'),
  wrong: require('../assets/sounds/wrong.wav'),
  tick: require('../assets/sounds/tick.wav'),
  alarm: require('../assets/sounds/alarm.wav'),
  win: require('../assets/sounds/win.wav'),
} as const;

export type SoundName = keyof typeof SOUND_SOURCES;

const players: Partial<Record<SoundName, AudioPlayer>> = {};

function getPlayer(name: SoundName): AudioPlayer {
  let player = players[name];
  if (!player) {
    player = createAudioPlayer(SOUND_SOURCES[name]);
    players[name] = player;
  }
  return player;
}

/** Plays a short UI sound effect, respecting the "الأصوات" setting. Never
 * throws — a failed sound should never interrupt gameplay. */
export async function playSound(name: SoundName): Promise<void> {
  if (!useSettingsStore.getState().soundEnabled) return;
  try {
    const player = getPlayer(name);
    await player.seekTo(0);
    player.play();
  } catch {
    // best-effort
  }
}
